//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCar.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCC()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }

        [StringLength(5, ErrorMessage = "Không được quá 5 kí tự ! ")]
        [Required(ErrorMessage = "Mã nhà cung cấp không được để trống !")]
        public string MaNCC { get; set; }
        [Required(ErrorMessage = "Tên nhà cung cấp không được để trống !")]
        public string TenNCC { get; set; }
        [Required(ErrorMessage = "Địa Chỉ không được để trống !")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "SĐT không được để trống !")]
        [StringLength(11, MinimumLength = 6, ErrorMessage = "Số kí tự cho SĐT thuộc [6-11] ")]
        [Range(0, int.MaxValue, ErrorMessage = "Số điện thoại không được chứa chữ")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống !")]
        public string Email { get; set; }
      

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
