//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCar.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
        }
    
        public string MaSP { get; set; }
       
        [MinLength(6, ErrorMessage = "Tên SP không dưới 6 kí tự ! ")]
        [Required(ErrorMessage = "Tên SP không được để trống !")]
        public string TenSP { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng không được chứa chữ")]
        [Required(ErrorMessage = "Số lượng không được để trống !")]
        public Nullable<int> SoLuong { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Đơn giá không được chứa chữ")]
        [Required(ErrorMessage = "Đơn giá không được để trống !")]
       
        public Nullable<decimal> DonGia { get; set; }

        public string MoTa { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Giá KM không được chứa chữ")]
       
        public Nullable<decimal> GiaKm { get; set; }
        // [DataType(DataType.ImageUrl)]
        //[DataType(DataType.Url)]
       
        public string URLAnh { get; set; }

        public string MaLoaiSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
