//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCar.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tintuc
    {
        public string MaTin { get; set; }
        
        public string URLAnh { get; set; }
        [Required(ErrorMessage = "Nội dung tin tức không được để trống !")]
        public string NoiDung { get; set; }
    }
}
